import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const OutfitFonts = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "Next Gen App",
  description: "Generated by create next Gen app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${OutfitFonts.className} h-full antialiased light`}
>
      <body className="min-h-full flex flex-col bg-background text-foreground">

        <Navbar/>
        <main>
          {children}
        </main>
        <Footer/>

        </body>
    </html>
  );
}
